function startup
%STARTUP Matlab startup-routine..
%   Sets additional search path to Toolboxes that are
%   specific to me as a user.

% Put the directory from where you startup Matlab below
% (you obviously have to make changes !):

MLHOME = '~/Desktop/';

cd(MLHOME)

addpath(['~/matlab/toolboxfunctions:'],...
        ['~/matlab/Gaussian Modes:'],...
        ['~/matlab/Optics:'],...
        ['~/matlab/QI:'],...
        ['~/matlab/Tomo Display:'],...
        ['~/matlab/Tomography:'],...
        ['~/Desktop/quantum chemistry/code/qubits:'],...
        ['~/matlab/processtomolinears:'],...
        ['~/matlab/errors:']);
        
