 %%-------new opt entangled
     %find optimal rotations
     function [fid, rho, optU] = find_best_rotation_Ben(rhoin)   
    standardpolns; standardbell
    rhotarg=phipm;%psipm;
    %the function below rotates the input state to get it close to psipm;
    fun=@(x)1-mixedfid(...
        rhotarg,...
    nkron(...
    arbUxzx([x(1) x(2) x(3)]),...
    arbUxzx([x(4) x(5) x(6)])...
         )...
    *rhoin*...
    nkron(...
    arbUxzx([x(1) x(2) x(3)]),...
    arbUxzx([x(4) x(5) x(6)])...
        )'...
    );


    x0=[1,1,1,1,1,1];
    x = fminsearch(fun,x0);

    Uopt=nkron(...
    arbUxzx(x(1:3)),...
    arbUxzx(x(4:6))...
         );

    rhoout=Uopt...
    *rhoin*...
    Uopt';

    fid=mixedfid(rhotarg,rhoout);

    rho=Uopt'*rhotarg*Uopt, rhoin;

    optU= Uopt;  