function Unitary = find_opt_U(rhoin, rhotarg)
fun=@(x)1-mixedfid(...
    rhotarg,...
nkron(...
arbUxzx([x(1) x(2) x(3)]),...
arbUxzx([x(4) x(5) x(6)])...
     )...
*rhoin*...
nkron(...
arbUxzx([x(1) x(2) x(3)]),...
arbUxzx([x(4) x(5) x(6)])...
    )'...
);


x0=[1,1,1,1,1,1];
x = fminsearch(fun,x0);

Unitary=nkron(...
arbUxzx(x(1:3)),...
arbUxzx(x(4:6))...
     );

% rhoout=Uopt...
% *rhoin*...
% Uopt';
%     
% out.fidopt(hh)=mixedfid(rhotarg,rhoout);

 